"""Drift guard: the packaged plugin copy must match the canonical source tree.

The repo ships a self-contained plugin under
``plugins/hardware-development-butler/scripts/`` that is a copy of the main
``tools/`` + ``embeddedskills/`` trees (generated by
``tools/package_hardware_butler_plugin.py``). Because it is a copy, every fix to
the canonical source must be re-packaged or the plugin ships a stale — possibly
insecure — version. This test fails loudly when the two diverge so a security
fix can never land in only one tree.

If this test fails, re-run::

    python tools/package_hardware_butler_plugin.py

to re-sync the plugin copy, then commit the result.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PLUGIN_SCRIPTS = REPO_ROOT / "plugins" / "hardware-development-butler" / "scripts"

# Trees that are copied verbatim into the plugin and must stay byte-identical.
SYNCED_TREES = ("tools", "embeddedskills")

# Root files the packager copies verbatim.
SYNCED_ROOT_FILES = (
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "conftest.py",
)

EXCLUDED_DIRS = {
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".tmp-pytest",
    ".tmp-plugin-smoke",
    ".mypy_cache",
    ".ruff_cache",
    "node_modules",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}


def _iter_source_files(tree: str) -> list[Path]:
    root = REPO_ROOT / tree
    files: list[Path] = []
    for path in root.rglob("*.py"):
        rel = path.relative_to(root)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        if path.suffix.lower() in EXCLUDED_SUFFIXES:
            continue
        files.append(path)
    return files


def _collect_synced_pairs() -> list[tuple[Path, Path, str]]:
    """Yield (canonical, plugin_copy, label) pairs that must be identical."""
    pairs: list[tuple[Path, Path, str]] = []
    for tree in SYNCED_TREES:
        for src in _iter_source_files(tree):
            rel = src.relative_to(REPO_ROOT)
            dst = PLUGIN_SCRIPTS / rel
            pairs.append((src, dst, str(rel).replace("\\", "/")))
    for name in SYNCED_ROOT_FILES:
        src = REPO_ROOT / name
        if src.exists():
            pairs.append((src, PLUGIN_SCRIPTS / name, name))
    return pairs


_PAIRS = _collect_synced_pairs()


@pytest.mark.skipif(not PLUGIN_SCRIPTS.is_dir(), reason="plugin copy not present")
@pytest.mark.parametrize("src,dst,label", _PAIRS, ids=[p[2] for p in _PAIRS])
def test_plugin_copy_matches_source(src: Path, dst: Path, label: str) -> None:
    """Every canonical source file must have a byte-identical plugin copy."""
    assert dst.exists(), (
        f"plugin copy missing for {label}; re-run "
        f"python tools/package_hardware_butler_plugin.py"
    )
    assert src.read_bytes() == dst.read_bytes(), (
        f"plugin copy of {label} has drifted from the canonical source; "
        f"re-run python tools/package_hardware_butler_plugin.py and commit"
    )


@pytest.mark.skipif(not PLUGIN_SCRIPTS.is_dir(), reason="plugin copy not present")
def test_sync_pairs_are_non_empty() -> None:
    """Guard against the collector silently matching zero files."""
    assert len(_PAIRS) > 50, (
        f"expected the plugin to mirror many source files, found {len(_PAIRS)}; "
        f"the sync check may be misconfigured"
    )
